import React, { useState } from 'react';

export default function LegalModal({ isOpen, onClose, initialTab = 'privacy' }) {
  const [tab, setTab] = useState(initialTab);

  if (!isOpen) return null;

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal-card legal-modal-card" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <div className="legal-tabs">
            <button
              type="button"
              className={`subtab-btn ${tab === 'privacy' ? 'active' : ''}`}
              onClick={() => setTab('privacy')}
            >
              🔒 Privacy Policy
            </button>
            <button
              type="button"
              className={`subtab-btn ${tab === 'terms' ? 'active' : ''}`}
              onClick={() => setTab('terms')}
            >
              ⚖️ Terms &amp; Disclaimers
            </button>
          </div>
          <button type="button" className="close-btn" onClick={onClose}>
            ✕
          </button>
        </div>

        <div className="legal-content">
          {tab === 'privacy' ? (
            <div className="legal-text-flow">
              <h4>1. Ephemeral Media Processing</h4>
              <p>
                All videos and stickers uploaded to or generated by this application are processed
                strictly inside isolated temporary storage directories. Files are purged
                automatically upon completion of your conversion or after an automated 15-minute TTL.
              </p>

              <h4>2. No Accounts or Tracking</h4>
              <p>
                We do not require user accounts, passwords, or personal credentials. We do not use
                invasive advertising cookies or behavioral tracking beacons.
              </p>

              <h4>3. Zero Content Logging</h4>
              <p>
                Our server logs contain purely operational metrics (unique request IDs, duration in
                seconds, response HTTP status codes, and output payload byte sizes). We strictly do not
                log video content, audio, or media filenames.
              </p>

              <h4>4. Safe URL Architecture (SSRF Prevention)</h4>
              <p>
                Our backend never fetches arbitrary remote URLs provided by users. Instagram links are
                validated client-side and sanitized cryptographically to prevent server-side request
                forgery.
              </p>
            </div>
          ) : (
            <div className="legal-text-flow">
              <h4>1. Permissible Use &amp; Intellectual Property</h4>
              <p>
                You may only convert media files that you own, have created, or for which you have
                received explicit license or authorization from the copyright holder. You agree not to
                generate unlawful, defamatory, or abusive stickers.
              </p>

              <h4>2. Independent Utility &amp; Trademark Disclaimers</h4>
              <p>
                <strong>Instagram</strong> and <strong>WhatsApp</strong> are registered trademarks of
                Meta Platforms, Inc. This application is an independent open-source tool and is not
                affiliated with, associated with, endorsed by, or sponsored by Meta Platforms, Inc. or
                any of its subsidiaries.
              </p>

              <h4>3. WhatsApp Sticker Standards Compliance</h4>
              <p>
                All stickers generated conform strictly to WhatsApp's published technical
                specifications: exactly 512×512 WebP canvas, ≤ 100 KB for static stickers, ≤ 500 KB and
                ≤ 10 seconds for animated stickers, and 96×96 PNG tray icons.
              </p>
            </div>
          )}
        </div>

        <div className="modal-footer">
          <button type="button" className="got-it-btn" onClick={onClose}>
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
